(() => {
  const canvas = document.querySelector('#canvas');
  const ctx = canvas.getContext('2d');
  const state = { objects: [], undone: [], camera: { x: 0, y: 0, zoom: 1 }, tool: 'pen', color: '#171717', size: 4, drawing: null, panning: null, selected: new Set() };
  const STORAGE_KEY = 'mindcanvas-v1';
  const $ = (s) => document.querySelector(s);
  const screen = (p) => ({ x: p.x * state.camera.zoom + state.camera.x, y: p.y * state.camera.zoom + state.camera.y });
  const world = (p) => ({ x: (p.x - state.camera.x) / state.camera.zoom, y: (p.y - state.camera.y) / state.camera.zoom });
  const point = (event) => ({ x: event.clientX, y: event.clientY });

  function resize() { const ratio = devicePixelRatio || 1; canvas.width = innerWidth * ratio; canvas.height = innerHeight * ratio; canvas.style.width = innerWidth + 'px'; canvas.style.height = innerHeight + 'px'; ctx.setTransform(ratio, 0, 0, ratio, 0, 0); render(); }
  function drawGrid() { const gap = 32 * state.camera.zoom; if (gap < 12) return; const x = state.camera.x % gap; const y = state.camera.y % gap; ctx.beginPath(); ctx.strokeStyle = '#ebeae5'; ctx.lineWidth = 1; for(let i=x; i<innerWidth; i+=gap){ctx.moveTo(i,0);ctx.lineTo(i,innerHeight)} for(let i=y;i<innerHeight;i+=gap){ctx.moveTo(0,i);ctx.lineTo(innerWidth,i)} ctx.stroke(); }
  function trace(obj) { if (obj.points.length < 2) return; ctx.beginPath(); const first = screen(obj.points[0]); ctx.moveTo(first.x, first.y); obj.points.slice(1).forEach(p => { const q=screen(p); ctx.lineTo(q.x,q.y); }); ctx.lineCap='round'; ctx.lineJoin='round'; ctx.strokeStyle=obj.color; ctx.lineWidth=obj.size * state.camera.zoom; ctx.globalAlpha=obj.tool === 'highlighter' ? .24 : obj.tool === 'brush' ? .55 : 1; ctx.stroke(); ctx.globalAlpha=1; }
  function render() { ctx.clearRect(0,0,innerWidth,innerHeight); drawGrid(); state.objects.forEach(o => { if (o.type === 'stroke') trace(o); else { const p=screen(o); ctx.fillStyle=o.color; ctx.font=`${o.size * state.camera.zoom}px Inter, sans-serif`; ctx.fillText(o.text,p.x,p.y); } }); if(state.drawing?.type==='lasso'){ const {start,end}=state.drawing; ctx.strokeStyle='#4b4b46';ctx.setLineDash([5,5]);ctx.strokeRect(start.x,start.y,end.x-start.x,end.y-start.y);ctx.setLineDash([]); } state.selected.forEach(i => {const o=state.objects[i];if(!o)return;const box=bounds(o);ctx.strokeStyle='#222';ctx.setLineDash([4,3]);ctx.strokeRect(box.x*state.camera.zoom+state.camera.x-5,box.y*state.camera.zoom+state.camera.y-5,box.w*state.camera.zoom+10,box.h*state.camera.zoom+10);ctx.setLineDash([])}); $('#zoomLabel').textContent=Math.round(state.camera.zoom*100)+'%'; }
  function bounds(o) { if(o.type==='text') return {x:o.x,y:o.y-o.size,w:o.text.length*o.size*.55,h:o.size*1.25}; const xs=o.points.map(p=>p.x),ys=o.points.map(p=>p.y);return{x:Math.min(...xs)-o.size,y:Math.min(...ys)-o.size,w:Math.max(...xs)-Math.min(...xs)+2*o.size,h:Math.max(...ys)-Math.min(...ys)+2*o.size}; }
  function save() { localStorage.setItem(STORAGE_KEY,JSON.stringify({objects:state.objects,camera:state.camera})); $('#hint').classList.toggle('hidden',state.objects.length>0); updateHistory(); }
  function updateHistory(){ $('#undoButton').disabled=!state.objects.length; $('#redoButton').disabled=!state.undone.length; }
  function commit(o) { if(o) state.objects.push(o); state.undone=[]; save(); render(); }
  function setTool(tool){ state.tool=tool; state.selected.clear(); document.querySelectorAll('.tool').forEach(b=>b.classList.toggle('active',b.dataset.tool===tool)); canvas.style.cursor=tool==='hand'?'grab':tool==='text'?'text':tool==='eraser'?'cell':'crosshair'; render(); }
  function removeAt(p){ let found=-1; for(let i=state.objects.length-1;i>=0;i--){let b=bounds(state.objects[i]);if(p.x>=b.x&&p.x<=b.x+b.w&&p.y>=b.y&&p.y<=b.y+b.h){found=i;break}} if(found>=0){state.undone.push(state.objects.splice(found,1)[0]);save();render();} }
  function zoomAt(factor, pivot={x:innerWidth/2,y:innerHeight/2}) { const old=world(pivot); state.camera.zoom=Math.min(8,Math.max(.1,state.camera.zoom*factor)); state.camera.x=pivot.x-old.x*state.camera.zoom;state.camera.y=pivot.y-old.y*state.camera.zoom; render();save(); }
  canvas.addEventListener('pointerdown', e=>{ if(e.button!==0)return; canvas.setPointerCapture(e.pointerId); const p=point(e), w=world(p); if(state.tool==='hand'||e.shiftKey){state.panning={p,c:{...state.camera}};return} if(state.tool==='eraser'){removeAt(w);return} if(state.tool==='text'){openTextEditor(p,w);return} if(state.tool==='lasso'){state.drawing={type:'lasso',start:p,end:p};render();return} state.drawing={type:'stroke',tool:state.tool,color:state.color,size:state.size,points:[w]}; });
  canvas.addEventListener('pointermove', e=>{const p=point(e);if(state.panning){state.camera.x=state.panning.c.x+p.x-state.panning.p.x;state.camera.y=state.panning.c.y+p.y-state.panning.p.y;render();return} if(!state.drawing)return;if(state.drawing.type==='lasso'){state.drawing.end=p;render();return} state.drawing.points.push(world(p));render();trace(state.drawing);});
  canvas.addEventListener('pointerup', ()=>{if(state.panning){state.panning=null;save();return}if(!state.drawing)return;if(state.drawing.type==='lasso'){const d=state.drawing, a=world({x:Math.min(d.start.x,d.end.x),y:Math.min(d.start.y,d.end.y)}), b=world({x:Math.max(d.start.x,d.end.x),y:Math.max(d.start.y,d.end.y)});state.selected.clear();state.objects.forEach((o,i)=>{const q=bounds(o);if(q.x+q.w>=a.x&&q.x<=b.x&&q.y+q.h>=a.y&&q.y<=b.y)state.selected.add(i)});state.drawing=null;render();return} const o=state.drawing;state.drawing=null;if(o.points.length>1)commit(o);else render();});
  canvas.addEventListener('wheel',e=>{e.preventDefault();zoomAt(e.deltaY<0?1.12:1/1.12,point(e));},{passive:false});
  function openTextEditor(p,w){const ed=$('#textEditor');ed.style.left=p.x+'px';ed.style.top=p.y+'px';ed.style.fontSize=(18*state.camera.zoom)+'px';ed.hidden=false;ed.textContent='';ed.focus();const finish=()=>{const text=ed.textContent.trim();ed.hidden=true;if(text)commit({type:'text',x:w.x,y:w.y,color:state.color,size:18,text});ed.removeEventListener('blur',finish)};ed.addEventListener('blur',finish);ed.onkeydown=e=>{if(e.key==='Escape'){ed.hidden=true;ed.blur()}if(e.key==='Enter'&&!e.shiftKey){e.preventDefault();ed.blur()}};}
  function download(name,type,data){const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([data],{type}));a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000);toast('Export complete');}
  function exportFile(kind){ if(kind==='json')return download('mindcanvas.json','application/json',JSON.stringify({version:1,objects:state.objects},null,2));if(kind==='svg'){let s=`<svg xmlns="http://www.w3.org/2000/svg" width="${innerWidth}" height="${innerHeight}" viewBox="${-state.camera.x/state.camera.zoom} ${-state.camera.y/state.camera.zoom} ${innerWidth/state.camera.zoom} ${innerHeight/state.camera.zoom}">`;state.objects.forEach(o=>{if(o.type==='text')s+=`<text x="${o.x}" y="${o.y}" fill="${o.color}" font-family="Inter, sans-serif" font-size="${o.size}">${o.text.replace(/&/g,'&amp;').replace(/</g,'&lt;')}</text>`;else s+=`<path d="M ${o.points.map(p=>p.x+' '+p.y).join(' L ')}" fill="none" stroke="${o.color}" stroke-width="${o.size}" stroke-linecap="round" stroke-linejoin="round" opacity="${o.tool==='highlighter'?'.24':'1'}"/>`});return download('mindcanvas.svg','image/svg+xml',s+'</svg>');} const out=document.createElement('canvas');out.width=innerWidth;out.height=innerHeight;out.getContext('2d').drawImage(canvas,0,0);out.toBlob(b=>download('mindcanvas.png','image/png',b)); }
  function toast(text){const t=$('#toast');t.textContent=text;t.classList.add('visible');setTimeout(()=>t.classList.remove('visible'),1600)}
  document.querySelectorAll('.tool').forEach(b=>b.onclick=()=>setTool(b.dataset.tool));$('#colorInput').oninput=e=>state.color=e.target.value;$('#sizeInput').oninput=e=>{state.size=+e.target.value;$('#sizeOutput').textContent=state.size};$('#undoButton').onclick=()=>{if(state.objects.length){state.undone.push(state.objects.pop());save();render()}};$('#redoButton').onclick=()=>{if(state.undone.length){state.objects.push(state.undone.pop());save();render()}};$('#clearButton').onclick=()=>{if(state.objects.length&&confirm('Clear everything on this canvas?')){state.undone.push(...state.objects);state.objects=[];save();render();toast('Canvas cleared')}};$('#homeButton').onclick=()=>{state.camera={x:0,y:0,zoom:1};save();render()};$('#zoomIn').onclick=()=>zoomAt(1.2);$('#zoomOut').onclick=()=>zoomAt(1/1.2);$('#zoomLabel').onclick=()=>{state.camera.zoom=1;render();save()};$('#exportButton').onclick=()=>{const m=$('#exportOptions');m.hidden=!m.hidden;$('#exportButton').setAttribute('aria-expanded',String(!m.hidden))};document.querySelectorAll('[data-export]').forEach(b=>b.onclick=()=>{$('#exportOptions').hidden=true;exportFile(b.dataset.export)});
  addEventListener('keydown',e=>{if(e.target.isContentEditable)return;if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='z'){e.preventDefault();e.shiftKey?$('#redoButton').click():$('#undoButton').click()}if(e.key===' '){setTool('hand');e.preventDefault()}const map={p:'pen',b:'brush',h:'highlighter',t:'text',e:'eraser',v:'lasso'};if(map[e.key.toLowerCase()])setTool(map[e.key.toLowerCase()]);});
  try {const saved=JSON.parse(localStorage.getItem(STORAGE_KEY));if(saved){state.objects=saved.objects||[];state.camera=saved.camera||state.camera}}catch{} resize();addEventListener('resize',resize);save();
})();
